### ISSUE TITLE
Add extension or new space for the SotN Randomizer

### ISSUE THREAD

**Issue by eldri7ch2** [video-game-randomizers/rando-list#11]
I have taken over Wild Mouse's Castlevania: Symphony of the Night Randomizer With a new website and updated features and options. 

The GitHub repository can be found here: https://github.com/eldri7ch2/SotN-Randomizer-Adv

The Website is here: https://sotnrando.net

**Comment by Die4Ever** [comment]
added, you can make a pull request if anything is incorrect or should be tweaked 

https://github.com/video-game-randomizers/rando-list/blob/main/src/series/Castlevania.yml#L36-L52

should the old one be marked as obsolete?

**Comment by eldri7ch2** [comment]
I wouldn't mark it as obsolete yet, but I would note that ours has more features at the moment. If there is a situation where the original creator decides to merge our changes within the next few months then I want to leave his up there (He still pops up in our circles, just no randomizer updates yet)

**Comment by Die4Ever** [comment]
I was looking at this again and maybe things are a bit mixed up?

https://github.com/video-game-randomizers/rando-list/blob/main/src/series/Castlevania.yml#L80-L93

the old one seems to be MottZilla's, but you mentioned Wild Mouse.

And then the newer one is 3snowp7im's at https://github.com/3snowp7im/SotN-Randomizer

But https://github.com/3snowp7im/SotN-Randomizer links to https://sotn.io/ same as MottZilla's

and then you mentioned https://sotnrando.net/ which we have in the comment for 3snowp7im's but it seems like there should be a new entry for eldri7ch2's?

Could you clear these things up or make a pull request? Maybe there should be 3 entries not 2? And maybe 1 of them should be marked as obsolete? Thanks.

**Comment by eldri7ch2** [comment]
Hey there! 

Yeah, never mind anymore. Wild Mouse came back and gave us access to update the original branch so we no longer need https;//sotnrando.net. I'm sorry for all of the confusion, we just didn't expect him to come back since he was gone for so long.

Thanks for your time!

**Comment by Die4Ever** [comment]
can you confirm this is all correct now? I don't remember if we confirmed already after that August 21st commit

**Comment by eldri7ch2** [comment]
Still wrong. I'll show you what I see and then explain what is real:

![image](https://github.com/user-attachments/assets/936fc6a3-6ac0-434b-856a-696fd0095d14)

Wild Mouse (3snow_p7im) only worked on the Relic / Item Randomizer for _PlayStation only_ here: https://sotn.io
↑ This is being maintained by me and a few others where we have added a *lot* of new features like Enemy Stat Randomizer and in December we're adding Shop Price Randomizer.

Mottzilla worked on the PlayStation Area Randomizer and the Sega Saturn Relic / Item Randomizer available at https://github.com/MottZilla/SOTN_AR
↑ This ARea Randomizer is _compatible_ with the Relic / Item Randomizer from SOTN.io

Additionally, Mottzilla is currently working on the Relic / Item Randomizer for XBLA Arcade versions of Symphony of the Night here https://github.com/MottZilla/SOTN_XB_RANDO

**Comment by Die4Ever** [comment]
Could you make a pull request to correct it?

**Comment by eldri7ch2** [comment]
I updated the yaml and tried to submit a PR but the auto-build didn't like it? I checked the yaml vs the suggested validator and it said it was good.
