### ISSUE TITLE
[Submission]: New galaxy generators for X3 Terran Conflict

### ISSUE THREAD

**Issue by tukkek** [video-game-randomizers/rando-list#30]
### URL Link

https://www.nexusmods.com/x3terranconflict/mods/121

### Game Series

X

### Game(s)

X3 Terran Conflict

### Summary

Galaxy generator.

### Open source?

- [ ] Open source

**Comment by tukkek** [comment]
### URL Link

https://www.moddb.com/mods/mayhem

### Game Series

X

### Game(s)

X3 Terran Conflict

### Summary

Galaxy generator (external tool bundled with the modification).

### Open source?

- [ ] Open source

**Comment by tukkek** [comment]
I'm not sure what is the relationship between these two or what relationship they have with the one already listed for X3... They seem to be completely different projects, from the couple of screen-shots I've seen.

Thought I'd share this here since I had no idea this game had a randomizer - let alone multiple! Hopefully it'll help others find them too.

Thanks for open-sourcing this list and keeping it alive! Cheers!

**Comment by Die4Ever** [comment]
added them in this commit: https://github.com/video-game-randomizers/rando-list/commit/2fbec3b38009f5c1bac88c45ef332e3078496432#diff-016f5b1ce73c428f22267c28c8996da5f66016d320178e7401c61608de9d05d6

thank you!

https://randomizers.debigare.com/#recent-randomizers
