### ISSUE TITLE
[Feature]: Make An APK Release

### ISSUE THREAD

**Issue by purrpgoddpeebles** [video-game-randomizers/rando-list#36]
### Summary

turn this project into a working APK for android phones so make it 32 bit and 64 bit compatible with armv7 and armv8 proccesors i myself still use an android 7.0 LGLV84 running nougat OS im sure hella peeps would appreciate an app or webapp of this project

**Comment by duncathan** [comment]
what would this achieve that the current site does not?

**Comment by ManicJamie** [comment]
I don't see why a mobile-compatible static website needs an android app, when you can just add a bookmark through your browser (and if my memory serves even add an icon shortcut to the launcher).

Any app we made would simply be a browser fetching the site anyway, or at most populating using a barebones API with the same data hosted in this repo. I see no potential upsides that cannot be achieved through improvements to the site as whole.
