### ISSUE TITLE
Fire Emblem 8 self randomizing ROM 2024 vesly with reclassing

### ISSUE THREAD

**Issue by joe9771** [video-game-randomizers/rando-list#44]
### URL Link

https://feuniverse.us/t/fe8-self-randomizing-rom-vesly-2024-version/25713

### Game Series

Fire Emblem

### Game(s)

Fire Emblem 8

### Summary

IT randomizes classes items characters pallets music growths ads and subtracts levels has a bunch of skills can be applied via the linked randomizer add-on and includes the reclassing system from Fates
![image](https://github.com/user-attachments/assets/57e28b0e-730c-4458-97f6-805eae2e6bb5)

### Open source?

- [X] Open source

**Comment by Die4Ever** [comment]
you marked this one as open source but I wasn't able to find the source code

**Comment by joe9771** [comment]
> you marked this one as open source but I wasn't able to find the source code 
Oops forgot to link this
https://feuniverse.us/t/self-randomizer-installer/25060/1
