### ISSUE TITLE
[Submission]: Kingdom Hearts RE: Chain of Memories Archipelago Randomizer

### ISSUE THREAD

**Issue by gaithern** [video-game-randomizers/rando-list#47]
### URL Link

https://github.com/gaithernOrg/ArchipelagoKHRECOM/

### Game Series

Kingdom Hearts

### Game(s)

Kingdom Hearts RE: Chain of Memories

### Summary

Randomizer exclusive for Archipelago.  Randomizes world cards, friend cards, sleights, Key to Rewards, and battle cards.

### Open source?

- [X] Open source

**Comment by duncathan** [comment]
as far as I know, we haven't decided what to do with randomizers that are only available as apworlds rather than being included in stable AP. since you're submitting three of them I'd say it's a good time for us to finally make a proper decision on the matter

**Comment by gaithern** [comment]
Understandable if not allowed!

**Comment by duncathan** [comment]
that's the funny thing: it's not *disallowed* either. I wouldn't mind either ruling but we really ought to make one lol
